## Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific Element", arr_2d[1, 2])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:, 1])

Specific Element 6
Entire Row:  [4 5 6]
Entire Column:  [2 5 8]


## Sorting

In [6]:
unsorted = np.array([3, 6, 2, 1, 8, 4, 5, 7, 9, 10])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1],
                            [1, 2],
                            [2, 3]])
print("Sorted 2D Array by Column: ", np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [ 1  2  3  4  5  6  7  8  9 10]
Sorted 2D Array by Column:  [[1 1]
 [2 2]
 [3 3]]


## Filter

In [8]:
number = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = number[number % 2 == 0]
print("Even Number: ", even_number)

Even Number:  [ 2  4  6  8 10]


## Filter with Mask

In [ ]:
mask = number > 5 # Mask stores expression
print("Numbers greater than 5: ", number[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [11]:
indices = [0, 2, 4]
print(number[indices])

where_result = np.where(number > 5)
print(where_result)
print("NP where: ", number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [13]:
condition_array = np.where(number > 5, number * 2, number)
print(condition_array )

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  False


In [19]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
