## Numpy array and basics
Learn about numpy with chai and oodes

In [1]:
import numpy as np

### Creating Array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [5]:
py_list = [1, 2, 3, 4, 5]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List Operation Time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array multiplication  [2 4 6]

 List Operation Time:  0.04079604148864746

 Numpy Operation Time:  0.004598140716552734


### Creating Array from Scratch

In [ ]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((3, 4))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2) # sequence is non inclusive of last element
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.12381935 0.27499773 0.3957532 ]
 [0.02841697 0.29254633 0.10969322]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [12]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [14]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape: ", arr.shape)  # number of rows and columns
print("Dimensions: ", arr.ndim)  # number of dimensions
print("Size: ", arr.size)  # total number of elements
print("Data type: ", arr.dtype) # data type

Shape:  (2, 3)
Dimensions:  2
Size:  6
Data type:  int64


### Array Reshaping

In [20]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape(
    (3, 4)
)
print("\n Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
